language: node_js
node_js:
- '6'
- '5'
script: npm run build

branches:
  only:
  - deploy
deploy:
  provider: heroku
  api_key:
        secure: qaQC1sRNWp7GNVANyChHESWhugacxnCZI9hGTywcwP4HYLh2wuk1IqnR1oNa6b56v3M9t33tyT9w3DvAPfq5gQNQ9A8sT05XQXbkfNeaUhnq1t62wdfuEdai0vFvBN1dRtUc51xs0orx37ODm8VGuRIRSbvToreWVSueChc6vgkMNcfJ8FquNt5Q5aF5QKsBfWIyhRMkvOJ1vlrdoJnCUX95dFQM4HjaleHVchulB8BiHKpCOMCBSPy7dPCmn+QHGKjABtC/hboytOtw3Fz5pXa5P46FF15BcM+7OstvpIYruv2Vpof5be5a1YxK8HYTvlm1kdRS64cRB0M0IQwrg0XRYgNq3sZoXBaCbk38C1JDNFOkixSPU3CL+minwkRXyoeVyYE810L1OJDt81mF6r7dlZvBTktEOjp/K5TDsEJtkK2LWlgizxA80n8Cu9gKt2E5SVpby74w1bIF4aUPW3rePNzyJVCEks2pXM4O4UZYjpuFqIH4dbfxCN5HeD/eJg1LffppR2sa/uU+0Z1jKdnOyR4B5D6nUv0gB+0puH8MwOlgBWLM0Pdgo+dNkOW9ylDSmsV68dTBNEiLeGPxiwzushO/X5gbj7fuLjUPwf7G3ZmV1s1HMIARqqesnRnm4Bhbk8449Qt5wwNqJ7Qa4xg2Lc8HS8ShrNJyS/wLwvg=
  app: cdp-travis-ci
  skip_cleanup: true
  on: deploy
